### PR TITLE
Changes to read SoH and SoC

### PR DESCRIPTION
**Pull request by clarkyncl**

### CODE REVIEW

**Comment by jverkoey** [comment]
Changes look good; can you share which model year you tested this on?

**Comment by clarkyncl** [comment]
It was 2022 :)

Sent on the move whilst bumping into things - excuse any typos!

Mike Proud
Managing Director
+44 333 323 8100
https://red-maple.co.uk
Read our email disclaimer and please consider the environment before printing this email. 
Should you have any doubts regarding the authenticity of this email, please verify by contacting us through our standard communication channels.
​Red Maple Consultants Ltd is a limited company registered in England and Wales. Registered number: 05780437. 
​Registered office: Unit 10, The Cowbarn, Vallum Farm, East Wallhouses, Newcastle upon Tyne, NE18 0LL
 
 
________________________________

**Comment by clarkyncl** [comment]
Saying that, think I need to look at the state of health more closely - I thought it was working but now it’s down to 68% while charge is at 65%.

Sent on the move whilst bumping into things - excuse any typos!

Mike Proud
Managing Director
+44 333 323 8100
https://red-maple.co.uk
Read our email disclaimer and please consider the environment before printing this email. 
Should you have any doubts regarding the authenticity of this email, please verify by contacting us through our standard communication channels.
​Red Maple Consultants Ltd is a limited company registered in England and Wales. Registered number: 05780437. 
​Registered office: Unit 10, The Cowbarn, Vallum Farm, East Wallhouses, Newcastle upon Tyne, NE18 0LL
 
 
________________________________

**Comment by jverkoey** [comment]
All good! Happy we're making progress toward the right values :D

**Pull request merged**
